### ISSUE TITLE
Finding Devices in Discovery Mode

### ISSUE THREAD

**Issue by bschiesser** [pwnieexpress/blue_hydra#88]
When using Blue Hydra with an Ubertooth One, we are only able to view bluetooth devices that are in discovery mode and we would like to know how to view devices that are not in discovery mode. Attached is the log file.
[blue_hydra.txt](https://github.com/pwnieexpress/blue_hydra/files/548556/blue_hydra.txt)

**Comment by ZeroChaos-** [comment]
I, [2016-10-19T10:17:57.736987 #3193]  INFO -- : Ubertooth thread starting
E, [2016-10-19T10:18:17.824744 #3193] ERROR -- : Error with ubertooth_{scan,rx}..
E, [2016-10-19T10:18:17.825253 #3193] ERROR -- : uh oh, full_usb_buf not emptied
E, [2016-10-19T10:18:52.033524 #3193] ERROR -- : Error with ubertooth_{scan,rx}..
E, [2016-10-19T10:18:52.033936 #3193] ERROR -- : uh oh, full_usb_buf not emptied
E, [2016-10-19T10:20:06.325315 #3193] ERROR -- : Error with ubertooth_{scan,rx}..
E, [2016-10-19T10:20:06.325725 #3193] ERROR -- : uh oh, full_usb_buf not emptied

maybe update your ubertooth firmware?

**Comment by bschiesser** [comment]
Our firmware is the most current, and we've done this with two Ubertooths, both updated.

**Comment by ZeroChaos-** [comment]
Some piece of your hardware is not working properly. The error you are getting (which is coming from ubertooth tools) says the buffer on the ubertooth is full and not being emptied fast enough. It is possible your usb is too slow, perhaps caused by a bad usb controller or driver. Either way this is not a blue hydra problem, the ubertooth tools are failing and we are just showing their error.
